name: saju_mobile_v1
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  api:
    path: packages/api
  bloc: ^8.1.4
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  kakao_flutter_sdk: ^1.9.7+3
  models:
    path: packages/models
  path_provider: ^2.1.5
  repository:
    path: packages/repository
  storage:
    path: packages/storage

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/.env

  fonts:
    - family: Hakgyoansim
      fonts:
        - asset: assets/fonts/Hakgyoansim.ttf
    - family: MapoFlowerIsland
      fonts:
        - asset: assets/fonts/MapoFlowerIsland.ttf
    - family: SSRock
      fonts:
        - asset: assets/fonts/SSRockRegular.ttf
    - family: NanumSquareNeo
      fonts:
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeo-aLt.ttf
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeo-bRg.ttf
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeo-cBd.ttf
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeo-dEb.ttf
        - asset: assets/fonts/nanum_square_neo/NanumSquareNeo-eHv.ttf
