name: api
description: api
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
dependencies:
  dio: ^5.8.0+1
  google_sign_in: ^6.3.0
  models:
    path: ../models
