name: saju_repository
description: Repository for the services
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  saju_local_storage:
    path: ../saju_local_storage

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
