name: repository
description: repository for tarot application
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  api:
    path: ../api
  dio: ^5.8.0+1
  models:
    path: ../models
  storage:
    path: ../storage

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
